<a href="https://colab.research.google.com/github/Niru27405/python_files/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating an array


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [ ]:
a=np.array(([1,2,3,4],[5,6,7,8]))
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
a=np.array(([1,2,3,4],[5,6,7,8],[2,4,6,8]))
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [ ]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr=np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arr=np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


Attributes of array:



In [ ]:
#shape of array
array=np.array(([2,3,4],[4,5,6]))
print(array)
print(array.shape)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [ ]:
#number of dimensions
array=np.array(([2,3,4],[4,5,6],[7,8,9]))
print(array)
print(array.ndim)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
2


In [ ]:
#array datatype
array=np.array(([2,3,4],[4,5,6],[7,8,9]))
print(array)
print(array.dtype)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
int64


In [ ]:
#array size
array=np.array(([2,3,4],[4,5,6],[7,8,9]))
print(array)
print(array.size)

[[2 3 4]
 [4 5 6]
 [7 8 9]]
9


Array Operations

In [ ]:
#array join
a=np.array(([2,3,4]))
b=np.array(([5,6,7]))
c=np.concatenate((a,b))
print(c)
d=np.array(([2,3,4],[4,5,6]))
e=np.array(([5,6,7],[4,5,6]))
f=np.concatenate((a,b))
print(c)

[2 3 4 5 6 7]
[2 3 4 5 6 7]
