<a href="https://colab.research.google.com/github/Niru27405/python_files/blob/main/CLA_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

13. Given an array of shape (4,4), split it into two equal halves and then stack them back together.   

In [10]:
import numpy as np
a = np.random.randint(1,101,size=(4,4))
print(a,"\n")
b,c= np.split(a,2)
print(b,"\n")
print(c,'\n')
v = np.vstack((b,c))
print(v)

[[23 32  1 18]
 [40 52 24 50]
 [48 29 61 26]
 [14 23 72  8]] 

[[23 32  1 18]
 [40 52 24 50]] 

[[48 29 61 26]
 [14 23 72  8]] 

[[23 32  1 18]
 [40 52 24 50]
 [48 29 61 26]
 [14 23 72  8]]



12. What is the difference between vstack() and hstack()?


In [13]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.vstack((a,b))
d = np.hstack((a,b))
print(c,"\n")
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


10.Create a multi-index DataFrame where the first level of the index represents Departments (IT, HR, Finance) and the second level represents Employee IDs (101, 102, 103). Assign random salaries and display the DataFrame.      

In [23]:
import pandas as pd
import numpy as np

a = pd.MultiIndex.from_product([['IT','HR','FINANCE'],[101,102,103]],names = ['Department','EMployee ID'])
Salaries = np.random.randint(1000,5000,len(a))
df = pd.DataFrame(Salaries,index = a)
print(df)

                           0
Department EMployee ID      
IT         101          4199
           102          4776
           103          4834
HR         101          4745
           102          4862
           103          1700
FINANCE    101          2527
           102          1785
           103          4879


11. (a) Create a DataFrame with the following data and display it. (2 Marks)
Name	Age	Score
David	21	78
Emma	25	92
Frank	22	85
________________________________________
(b) Select and display the "Score" column and retrieve the row where the Name is "Emma". (2 Marks)
________________________________________
(c) From the DataFrame, filter students who scored more than 80 and sort them by Age in descending order. (2 Marks)
________________________________________
(d) Assign performance levels based on the scores using the following criteria: (4 Marks)
•	Score ≥ 90 → "Excellent"
•	Score ≥ 80 and < 90 → "Good"
•	Score < 80 → "Needs Improvement"


In [34]:
import pandas as pd
data = {'Name':['David','Emma','Frank'],'Age':[21,25,22],'Score':[78,92,85]}
df = pd.DataFrame(data)
print(df)
c = df[df['Score']>80].sort_values(by='Age',ascending=False)
print(c)
print(df['Score'])
print(df[df['Name']=='Emma'])
def b(Score):
  if Score>=90:
    return 'Excellent'
  elif 80>= Score >90:
    return 'Good'
  else:
    return 'Needs Improvement'

df['Performance']=df['Score'].apply(b)
print(df)

    Name  Age  Score
0  David   21     78
1   Emma   25     92
2  Frank   22     85
    Name  Age  Score
1   Emma   25     92
2  Frank   22     85
0    78
1    92
2    85
Name: Score, dtype: int64
   Name  Age  Score
1  Emma   25     92
    Name  Age  Score        Performance
0  David   21     78  Needs Improvement
1   Emma   25     92          Excellent
2  Frank   22     85  Needs Improvement


7.Create a Pandas Series with custom index labels ['A', 'B', 'C', 'D', 'E'] and values [10, 20, 30,  40, 50]. Retrieve the element at index "C".

In [42]:
import pandas as pd
a = pd.Series([10,20,30,40,50],index = ['f','b','c','d','e'])
print(a['c'])


30


6. Describe about array slicing and do the following: (1 mark)
      a)Given the array arr = np.array([10, 20, 30, 40, 50, 60, 70, 80]), extract elements from index  
         2 to 5
      b) Negative Slicing: extract elements from index -2 to -5       


In [48]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80])
print(arr[2:6])
print(arr[-2:-6:-1])

[30 40 50 60]
[70 60 50 40]


5.Write a program to sort a NumPy array along both rows and columns.

In [53]:
import numpy as np
data = np.array([[2,6,4],[60,20,80],[13,56,41]])
print(data,'\n')
c = np.sort(data,axis=0)
print(c,'\n')
d = np.sort(data)
print(d)

[[ 2  6  4]
 [60 20 80]
 [13 56 41]] 

[[ 2  6  4]
 [13 20 41]
 [60 56 80]] 

[[ 2  4  6]
 [20 60 80]
 [13 41 56]]


1. Write a Python program to create a NumPy array of shape (3,4) filled with random integers between 1 and 100.

In [54]:
import numpy as np
data = np.random.randint(1,101,size=(3,4))
print(data)

[[35 70 21 54]
 [87 17 81 93]
 [74 69 80 56]]


2.Implement a Python program that performs the following NumPy operations:
•	Joins two arrays                                       
•	Splits an array into three parts and Sorts an array in ascending order   


In [60]:
import numpy as np
w= np.array([10,20,30])
q = np.array([40,50,60,70,80,90])
x = np.concatenate((w,q))
print(x)
d = np.split(q,2)
s = np.sort(d)
print(d)
print(s)

[10 20 30 40 50 60 70 80 90]
[array([40, 50, 60]), array([70, 80, 90])]
[[40 50 60]
 [70 80 90]]


3.Given two NumPy arrays, A = np.array([1, 2, 3]) and B = np.array([4, 5, 6]), perform the following operations:
•	Element-wise addition
•	Element-wise multiplication
•	Dot product                           


In [63]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A+B)
print(A*B)
print(np.dot(A,B))

[5 7 9]
[ 4 10 18]
32


4. Write a Pandas program that:
•	Reads a dataset and Selects specific columns                                      
•	Filters rows based on a condition            
•	Sorts the DataFrame based on a column  


In [64]:
import pandas as pd
df = pd.read_csv('arr.csv')
print(df[['Name','Age','Salary']])
c = df[df['Age']>30]
print(c)
d = df.sort(by='Age',ascending = False)
print(d)

14. Explain about Stacking and Unstacking in DataFrames.                                   

In [73]:
import pandas as pd
data = {'A':[1,2],'B':[3,4]}
df = pd.DataFrame(data,index=['x','y'])
d = df.stack()
f = df.unstack()
print(d)
print(f)

x  A    1
   B    3
y  A    2
   B    4
dtype: int64
A  x    1
   y    2
B  x    3
   y    4
dtype: int64


9. Discuss in detail about stacking and its types. Justify how it is differentiated with an example   

In [78]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.dstack((a,b)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


8. Illustrate on  column operations in pandas data frame with an example     

In [89]:
import pandas as pd
data = {'Name':['Joy','Roy','Tom','Ron'],'Age':[12,14,18,15]}
df = pd.DataFrame(data)
print(df)
df['Salary']=[1000,6000,5000,8000]
print(df)
print(df[df['Age']>15])
a = df.sort_values(by='Age',ascending=False)
print(a)

  Name  Age
0  Joy   12
1  Roy   14
2  Tom   18
3  Ron   15
  Name  Age  Salary
0  Joy   12    1000
1  Roy   14    6000
2  Tom   18    5000
3  Ron   15    8000
  Name  Age  Salary
2  Tom   18    5000
  Name  Age  Salary
2  Tom   18    5000
3  Ron   15    8000
1  Roy   14    6000
0  Joy   12    1000
