<a href="https://colab.research.google.com/github/Niru27405/python_files/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas - Series
Series is a data structure
only 1D data can be created

Initialize a series from list

In [ ]:
import pandas as pd
data = [1,2,3,4,5]
S = pd.Series(data)
print(S)

0    1
1    2
2    3
3    4
4    5
dtype: int64


Initialize a Series from a dictionary

In [ ]:
import pandas as pd
data = {'a':1,'b':2,'c':3}
a = pd.Series(data)
print(a)

a    1
b    2
c    3
dtype: int64


Initialize a Series with custom index

In [ ]:
import pandas as pd
data = [1,2,3,4,5]
index = ['a','b','c','d','e']
a = pd.Series(data,index = index)
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
import pandas as pd
data = [23,35,46,57,12,18,29]
index = ['Ram','Isha','Elsa','Tom','Riya','Bunny','Sherya']
a = pd.Series(data,index = index)
print(a)


Ram       23
Isha      35
Elsa      46
Tom       57
Riya      12
Bunny     18
Sherya    29
dtype: int64


Series Addition - Arithmetic Operations

In [ ]:
import pandas as pd
a = pd.Series([1,2,3])
b = pd.Series([4,5,6])
sum = a+b
print(sum)

0    5
1    7
2    9
dtype: int64


Combining and printing if the index is available in both a and b

In [ ]:
import pandas as pd
a = pd.Series([1,2,3],index= ['a','b','c'])
b = pd.Series([4,5,6],index= ['b','c','d'])
sum = a+b
print(sum)

a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64


Data Frames

In [ ]:
import pandas as pd
data = {'Name': ['John','Alice','Bob'],'Age':[25,30,35],'City':['New York','Los Angeles','Chicago']}
df = pd.DataFrame(data)
print(df)

    Name  Age         City
0   John   25     New York
1  Alice   30  Los Angeles
2    Bob   35      Chicago


. Calculate the total items sold for each product over the week.


In [ ]:
import pandas as pd
data = {'Day':['Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday'],'Bread':[20,25,22,30,35,40],'Cakes':[15,18,16,20,25,30],'Cookies': [50,55,52,60,65,70],'Muffins':[10,12,11,15,20,25],'Pies':[5,6,7,10,15,18]}
df = pd.DataFrame(data)
# df.loc[6]=['Cp',10,50,5,12,20]
a_sum = np.sum(data,axis = 0)
print(a_sum)

{'Day': ['Monday', 'Tuesday', 'Wednesday', 'Thrusday', 'Friday', 'Saturday'], 'Bread': [20, 25, 22, 30, 35, 40], 'Cakes': [15, 18, 16, 20, 25, 30], 'Cookies': [50, 55, 52, 60, 65, 70], 'Muffins': [10, 12, 11, 15, 20, 25], 'Pies': [5, 6, 7, 10, 15, 18]}


. Find the average number of items sold for each product across all days

In [ ]:
import pandas as pd
data = {'Day':['Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday'],'Bread':[20,25,22,30,35,40],'Cakes':[15,18,16,20,25,30],'Cookies': [50,55,52,60,65,70],'Muffins':[10,12,11,15,20,25],'Pies':[5,6,7,10,15,18]}
df = pd.DataFrame(data)
# df.loc[6]=['Cp',10,50,5,12,20]
a_mean = df.iloc[:,1:].mean()
print(a_mean)


Bread      28.666667
Cakes      20.666667
Cookies    58.666667
Muffins    15.500000
Pies       10.166667
dtype: float64


Determine the total revenue for the week if the selling prices of bread,
cakes, cookies, muffins, and pies are $15, $70, $8, $18, and $30,
respectively.

In [ ]:
import pandas as pd
data = {'Day':['Monday','Tuesday','Wednesday','Thrusday','Friday','Saturday'],'Bread':[20,25,22,30,35,40],'Cakes':[15,18,16,20,25,30],'Cookies': [50,55,52,60,65,70],'Muffins':[10,12,11,15,20,25],'Pies':[5,6,7,10,15,18]}
df = pd.DataFrame(data)
cp = {'CP':[10,50,5,12,20]}

CLA-I Practice

Creating one-dimensional array in NumPy

In [ ]:
import numpy as np
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Check the dimensions by using array.shape.
(20, )


In [ ]:
import numpy as np
arr = np.arange(20)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)


b. Creating two-dimensional arrays in NumPy

In [ ]:
import numpy as np
arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
import pandas as pd
data = [1,2,3,4,5]
a = pd.Series(data)
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
import pandas as pd
a = pd.Series([1,2,3])
b = pd.Series([4,5,6])
sum = a+b
print(sum)

0    5
1    7
2    9
dtype: int64


In [6]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9])
b = np.split(a,3)
c = np.sort(b)
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
c = A + B
d = A * B
e = np.dot(A,B)
print(c,d,e)

[5 7 9] [ 4 10 18] 32


In [29]:
import pandas as pd
a = {'Name':['Joy','Roy','Don'],'Age':[10,12,14],'Salary':[2000,4000,6000]}
b = pd.DataFrame(a)
c = b[['Name','Age']]
print(c)
d = b[b['Salary']>2000]
e = b.sort_values(by = 'Salary',ascending = False)
# print(a['Age'])
# print(e)
# print(d)


  Name  Age
0  Joy   10
1  Roy   12
2  Don   14


In [38]:
import numpy as np
a = np.random.randint(1,101,size=(3,4))
print(a,'\n')

b = np.sort(a,axis = 0)
print(b,'\n')
c = np.sort(a,axis = 1)
print(c,'\n')

[[52 27 73 43]
 [16 11 35 38]
 [71 69 54 92]] 

[[16 11 35 38]
 [52 27 54 43]
 [71 69 73 92]] 

[[27 43 52 73]
 [11 16 35 38]
 [54 69 71 92]] 



In [41]:
import pandas as pd
a = pd.Series([10,20,30,40,50],index =['A','B','C','D','E'])

print(a['C'])

30


In [49]:
import numpy as np
a = np.array([10,20,30,40,50,60,70,80])
print(a[2:6])
print(a[-5:-2])


[30 40 50 60]
[40 50 60]
